name: Post Merge

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions:
  contents: read

concurrency: s3-to-firehose-post-merge

jobs:
  tests:
    uses: ./.github/workflows/_run-tests.yml

  tag-release:
    if: "contains(github.event.head_commit.message, '[automated release]')"
    needs:
      - tests
    permissions:
      contents: write
    uses: govuk-pay/pay-ci/.github/workflows/_create-alpha-release-tag.yml@591ff32de6cd3c9a0f4af2506f8938e7bd5decaa
